update maven.yml file

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -15,7 +15,7 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Set up JDK 21
+      - name: Set up JDK 23
         uses: actions/setup-java@v4
         with:
           java-version: '23'
@@ -33,4 +33,7 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AppointmentSchedulingSystem_Appointment-Scheduling-System
+        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AppointmenSchedulingSystem_Appointment-Scheduling-System -Dsonar.organization=appointmenschedulingsystem
+
+      - name: Check JaCoCo report
+        run: find /home/runner/work -name "jacoco.xml" 2>/dev/null || echo "Not found"
